name = "test_shell_debug"
version = "0.1.0"

[fortran]
implicit-typing = false  # Enforces implicit none
implicit-external = false
source-form = "free"

[[executable]]
name = "test_shell_debug"
main = "main.f90"

[executable.dependencies]
