name: Debug Windows Paths

on:
  push:
    branches: [ debug-windows-paths ]

jobs:
  debug-paths:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup MinGW (MSYS2)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        path-type: inherit
        install: >-
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-gcc
          git

    - name: Add MinGW to PATH
      run: echo C:\msys64\mingw64\bin | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh

    - name: Install FPM
      shell: pwsh
      run: |
        Write-Host "Installing FPM directly from GitHub releases..."
        Invoke-WebRequest -Uri "https://github.com/fortran-lang/fpm/releases/download/v0.12.0/fpm-0.12.0-windows-x86_64-gcc-12.exe" -OutFile "fpm.exe"
        Move-Item -Path "fpm.exe" -Destination "C:\msys64\mingw64\bin\fpm.exe"
        & "C:\msys64\mingw64\bin\fpm.exe" --version

    - name: Build project
      run: |
        echo Building project...
        fpm build --compiler gfortran
      shell: cmd

    - name: Compile and run simple debug test
      run: |
        echo Compiling simple Windows path debug test...
        gfortran -o test_windows_paths_simple.exe test\windows\test_windows_paths_simple.f90
        
        echo.
        echo Running simple debug test...
        test_windows_paths_simple.exe
      shell: cmd
    
    - name: Run preprocessor test with timeout
      run: |
        echo Running preprocessor test with debug output...
        
        REM Set single-threaded execution for CI stability
        set OMP_NUM_THREADS=1
        set FORTRAN_CI=true
        set CI=true
        
        REM Check current directory and file paths
        echo Current directory: %CD%
        dir example\basic\hello\hello.f
        dir example\basic\hello\hello.f90
        
        REM Run test with a timeout to prevent hanging
        REM Using start /B with timeout to allow graceful termination
        start /B fpm test test_examples > test_output.log 2>&1
        
        REM Wait up to 60 seconds then check output
        timeout /t 60 /nobreak >nul
        
        REM Show relevant output
        type test_output.log | findstr /i "preprocessor specified invalid debug path"
        
        echo Test completed (or timed out)
      shell: cmd
      continue-on-error: true

    - name: Check test artifacts
      shell: pwsh
      run: |
        Write-Host "Checking for any remaining temp files..."
        Get-ChildItem -Path $env:TEMP -Filter "*fortran_test*" -ErrorAction SilentlyContinue | ForEach-Object {
            Write-Host "Found temp artifact: $($_.FullName)"
        }