name: Test Coverage

on: [push, pull_request]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Fortran Package Manager
      run: |
        wget https://github.com/fortran-lang/fpm/releases/download/v0.12.0/fpm-0.12.0-linux-x86_64-gcc-12
        chmod +x fpm-0.12.0-linux-x86_64-gcc-12
        sudo mv fpm-0.12.0-linux-x86_64-gcc-12 /usr/local/bin/fpm

    - name: Install GFortran and gcov
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran gcovr

    - name: Build with coverage flags
      run: |
        fpm build --flag '-fprofile-arcs -ftest-coverage'

    - name: Run tests with coverage
      run: |
        fpm test --flag '-fprofile-arcs -ftest-coverage'

    - name: Generate coverage report
      run: |
        gcovr --root . --exclude 'build/*' --xml -o coverage.xml --print-summary

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true