name: Test Coverage

on: [push, pull_request]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Fortran Package Manager
      run: |
        wget https://github.com/fortran-lang/fpm/releases/download/v0.12.0/fpm-0.12.0-linux-x86_64-gcc-12
        chmod +x fpm-0.12.0-linux-x86_64-gcc-12
        sudo mv fpm-0.12.0-linux-x86_64-gcc-12 /usr/local/bin/fpm

    - name: Install GFortran and gcov
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran gcovr imagemagick

    - name: Run install script and build with coverage flags
      run: |
        chmod +x install.sh
        ./install.sh --flag '-fprofile-arcs -ftest-coverage'

    - name: Run comprehensive coverage with Makefile
      run: |
        # Use Makefile coverage target that runs ALL tests comprehensively
        make coverage
        # Generate XML for codecov  
        gcovr --root . \
          --exclude 'build/*' \
          --exclude 'test/*' \
          --exclude 'example/*' \
          --exclude 'app/test_*.f90' \
          --exclude 'draft/*' \
          --xml -o coverage.xml \
          --print-summary

    - name: Test installed binary
      run: |
        # Test that the installed binary works
        export PATH="$HOME/.local/bin:$PATH"
        echo 'program test_install; print *, "Install test successful"; end program' > test_install.f90
        fortran test_install.f90
        rm -f test_install.f90

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
