name: Windows Integration Tests

# Windows-specific integration tests (smoke tests, cache functionality, module resolution)
# Unit tests run in the main test.yml workflow

on:
  push:
    branches: [ main, windows-support ]
  pull_request:
    branches: [ main, windows-support ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [gfortran]
        include:
          - compiler: gfortran
            fc: gfortran

    steps:
    - uses: actions/checkout@v4

    - name: Setup MinGW (MSYS2)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        path-type: inherit
        install: >-
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-gcc
          git

    - name: Add MinGW to PATH
      run: echo C:\msys64\mingw64\bin | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh

    - name: Install FPM
      shell: pwsh
      run: |
        Write-Host "Installing FPM directly from GitHub releases..."
        Invoke-WebRequest -Uri "https://github.com/fortran-lang/fpm/releases/download/v0.12.0/fpm-0.12.0-windows-x86_64-gcc-12.exe" -OutFile "fpm.exe"
        Move-Item -Path "fpm.exe" -Destination "C:\msys64\mingw64\bin\fpm.exe"
        & "C:\msys64\mingw64\bin\fpm.exe" --version

    - name: Test Windows environment
      run: |
        Write-Host "Environment diagnostics:"
        Write-Host "TEMP: $env:TEMP"
        Write-Host "TMP: $env:TMP"
        Write-Host "LOCALAPPDATA: $env:LOCALAPPDATA"
        Write-Host "USERPROFILE: $env:USERPROFILE"
        Write-Host "Current directory: $pwd"
      shell: powershell

    - name: Build project
      run: |
        echo Building project...
        if exist build rmdir /s /q build
        fpm build --compiler gfortran --flag="-cpp"
      shell: cmd

    - name: List build directory
      run: |
        echo "Listing build directory contents:"
        dir /s /b build
      shell: cmd

    - name: Run unit tests
      run: |
        echo Running critical unit tests only on Windows CI...

        REM Set single-threaded execution for CI stability
        set OMP_NUM_THREADS=1
        set FORTRAN_CI=true
        
        REM Run only critical tests that don't use fortran CLI
        REM Skip all integration tests on Windows CI
        echo N | fpm test test_parse_multi_decl
        echo N | fpm test test_lexer_direct
        echo N | fpm test test_string_utils
        echo N | fpm test test_logger
        echo N | fpm test test_os_detection
        
        echo Critical unit tests passed!
        echo NOTE: Full test suite skipped on Windows CI due to performance constraints
        echo Please run full tests locally on Windows before merging
      shell: cmd

    - name: Run smoke tests
      run: |
        echo Running smoke tests...

        REM Find the built executable by checking specific pattern
        set "FORTRAN_EXE="
        for /f "tokens=*" %%i in ('dir /s /b build 2^>nul ^| findstr "\\app\\fortran.exe$" ^| findstr /v "dependencies"') do set "FORTRAN_EXE=%%i"
        if "%FORTRAN_EXE%"=="" (
          echo ERROR: Could not find fortran.exe in build/app directory
          echo Searching for any fortran.exe in build directory:
          dir /s /b build | findstr "fortran.exe" | findstr /v "dependencies"
          exit /b 1
        )
        echo Found executable: %FORTRAN_EXE%

        REM Test version flag
        echo Testing --version flag...
        "%FORTRAN_EXE%" --version
        if %ERRORLEVEL% NEQ 0 (
          echo ERROR: --version flag failed
          exit /b 1
        )

        REM Run basic smoke test (simple lowercase fortran without program wrapper)
        echo print *, 'x = 42' > test_windows.f

        REM Create a temp cache directory
        if not exist temp_cache mkdir temp_cache

        REM Run the executable with the test file using custom cache
        "%FORTRAN_EXE%" --cache-dir "%CD%\temp_cache" "%CD%\test_windows.f" -v
        if %ERRORLEVEL% NEQ 0 (
          echo ERROR: Failed to run test file
          echo Trying with more verbose output:
          "%FORTRAN_EXE%" --cache-dir "%CD%\temp_cache" "%CD%\test_windows.f" -vv
          exit /b 1
        )

        REM Clean up
        del /f test_windows.f
        rmdir /s /q temp_cache

        echo Smoke tests passed
      shell: cmd

    - name: Test cache functionality
      run: |
        # Create a local cache directory
        $cache_dir = Join-Path $pwd "test_cache"
        Write-Host "Creating cache directory at: $cache_dir"
        New-Item -ItemType Directory -Path $cache_dir -Force | Out-Null

        # Find the fortran executable
        $fortran_exe = Get-ChildItem -Path "build" -Recurse -Filter "fortran.exe" | Select-Object -First 1
        if ($null -eq $fortran_exe) {
          Write-Host "ERROR: Could not find fortran.exe in build directory"
          exit 1
        }
        Write-Host "Found executable: $($fortran_exe.FullName)"

        # Test version
        & $fortran_exe.FullName --version

        # Test with a simple example using custom cache
        $test_file = Join-Path $pwd "test_windows.f"
        Set-Content -Path $test_file -Value 'real :: x = 3.14'
        Write-Host "Test file created at: $test_file"

        # Run with custom cache directory
        & $fortran_exe.FullName --cache-dir $cache_dir $test_file

        # Clean up
        Remove-Item $test_file -Force
        Remove-Item $cache_dir -Recurse -Force
      shell: powershell

    - name: Test module resolution
      run: |
        # Test module resolution functionality
        New-Item -ItemType Directory -Path "test_modules" -Force

        # Create module file
        "module test_mod" | Out-File -FilePath "test_modules\test.f90" -Encoding ASCII
        "  implicit none" | Out-File -FilePath "test_modules\test.f90" -Append -Encoding ASCII
        "  real :: pi = 3.14159" | Out-File -FilePath "test_modules\test.f90" -Append -Encoding ASCII
        "end module test_mod" | Out-File -FilePath "test_modules\test.f90" -Append -Encoding ASCII

        # Create main program
        "program test_prog" | Out-File -FilePath "test_modules\main.f90" -Encoding ASCII
        "  use test_mod" | Out-File -FilePath "test_modules\main.f90" -Append -Encoding ASCII
        "  implicit none" | Out-File -FilePath "test_modules\main.f90" -Append -Encoding ASCII
        "  print *, pi" | Out-File -FilePath "test_modules\main.f90" -Append -Encoding ASCII
        "end program test_prog" | Out-File -FilePath "test_modules\main.f90" -Append -Encoding ASCII

        # Find the fortran executable
        $fortran_exe = Get-ChildItem -Path "build" -Recurse -Filter "fortran.exe" | Select-Object -First 1

        # Run from test_modules directory
        Push-Location test_modules
        & $fortran_exe.FullName main.f90
        Pop-Location

        # Clean up
        Remove-Item -Recurse test_modules -Force
      shell: powershell

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fortran-windows-${{ matrix.compiler }}
        path: build/*/app/fortran.exe
        retention-days: 30

